# Generated by Django 3.0.7 on 2020-06-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibmUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
