# Generated by Django 3.0.7 on 2020-06-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibmUsers', '0002_user_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_test',
        ),
    ]
