# Generated by Django 2.2.13 on 2020-07-19 03:25

from django.db import migrations, models
import django.db.models.deletion
import ibmLMS.ibmCustomStorage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.PositiveSmallIntegerField(verbose_name='class section ID')),
                ('start_time', models.TimeField(verbose_name='class start time')),
                ('end_time', models.TimeField(verbose_name='class end time')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='course name')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='document name')),
                ('available_at', models.DateTimeField(verbose_name='document available start date')),
                ('available_until', models.DateTimeField(verbose_name='document available end date')),
                ('document', models.FileField(storage=ibmLMS.ibmCustomStorage.IbmStorage(), upload_to='')),
                ('part_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='course_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses', verbose_name='Course part'),
        ),
    ]
