# Generated by Django 2.2.13 on 2020-07-19 03:25

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibmUsers', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='ibmUsers.Student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='ibmUsers.Teacher'),
        ),
    ]
